config/routes.rb
require 'sidekiq/web'
Aries::Application.routes.draw do

  constraints(Subdomain) do
    match '/' => 'stores#show'
    post '/orders' => 'orders#create'
    post '/requests' => 'requests#create'
    match "/:number" => "products#show",:as => "product"
  end
  
  mount Sidekiq::Web, at: "/sidekiq"

  root :to => "home#index"
  
  
  resources :file_handlers
  resources :orders do
    resources :comments,:only => [:new,:create,:show] 
  end
  
  
  resources :home do
    collection do
      get :subscriptions
      get :stories
      get :recommendations
    end
  end
  
  get '/find_friends', to: 'settings#find_friends', as: :find_friends

  get "new/create"

  get "new/destroy"
  get 'tags/:tag', to: 'products#index', as: :tag
  get '/notifications', to: 'settings#user_notifications', as: :notifications
  devise_for :users

  match "auth/:provider/callback" => "social_sites#create"
  
  resources :user_registrations,:only => [:new,:create] do
    collection do
      get :confirm_account
      put :resend_confirmations
    end
  end
  
  resources :dashboard do
    collection do
      get :products 
      get :orders
      get :views
      get :reviews
    end
  end
  
  resources :settings,:except => [:new,:create,:show,:edit,:update,:index,:destroy],:path => '/dashboard/settings/' do
    member do
      get :notifications
      post :create_notification
      get :edit_notifications
      put :notification_updation
    end
    collection do
      get :account
      put :update_account
      get :social
      post :send_twitter_message
      get :complete_social_signup
      put :update_social_signup
    end
  end
  resources :stores, :except =>[:show]
  resources :products,:except => [:show,:edit,:update] do
    member do
      get :payment
      put :recommend
      put :post_product
    end
    
    collection do
      get :top_products
      put :product_delete
    end
  end

  resources :profiles, :except => [:show] do
    collection do
      get :balance
      get :shopping
      get :referral
    end
    member do
      get :subscriptions, :subscribers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :requests, only: [:index]
  resources :activities, only: [:index]
  resources :questions, except: [:new, :edit] do
    collection do
      get :answered
      get :your_questions
    end
    resources :answers, only: [:new,:create]
  end
  resources :themes
  
  match "/discover" => "discover#discover"
  match "/discover/products" => "discover#product"
  match "/discover/shops" => "discover#shop"
  match "/discover/people" => "discover#people"
  match "/discover/tags" => "discover#tags"
  match "/products/add" => "products#add", :as => "add_product"
  match "/listing/:id" => "products#listing_complete", :as => "listing"
  match "customise/:username" => "stores#customise"
  match 'products/:product_id/make_payment' => 'products#make_payment', :as => :confirm_payment
  match "/products/:number/edit" => "products#edit",:as => "edit_product"
  match "/products/:number" => "products#update",:as => "update_product"
  match "/products/:random_no/download_product" => 'products#download_product',:as => 'download'
  match "profiles/:username" => "profiles#show"
  match "profiles/:username/drawer" => "profiles#drawer", :as => "drawer"
  match "profiles/:username/recommendations" => "profiles#recommends", :as => "recommends"
  match "profiles/:username/activities" => "profiles#activities", :as => "activities"
  match "stores/update_theme_content" => "stores#update_theme_content"
  match "/update_custom_appearance" => "stores#custom_appearance_update"
  post  "/shipping_option", to: "stores#add_shipping_profiles"

  

end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id                   :integer          not null, primary key
#  user_id              :integer
#  store_name           :string(255)
#  delivery_returns     :text
#  more_info            :text
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  currency             :string(255)
#  terms_conditions     :boolean
#  store_url            :string(255)
#  show_recommendations :boolean
#  ask_questions        :boolean
#  ask_page_title       :string(255)
#  views                :integer          default(0)
#  unique_views         :integer          default(0)
#  theme_name           :string(255)
#  payout_email         :string(255)
#  custom_theme_content :text
#  store_terms :text
#

class Store < ActiveRecord::Base
  serialize :custom_appearance, ActiveRecord::Coders::Hstore
  attr_accessible :store_name,:delivery_returns,:more_info,:terms_conditions,:store_url,:show_recommendations,
                  :ask_questions, :ask_page_title,:theme_name,:custom_theme_content,:payout_email ,:store_terms, :original_theme_id,:currency
  belongs_to :user
  validates_uniqueness_of :store_name
  validates :store_name,:presence => true
  has_many :products,:dependent => :destroy
  has_many :store_views, class_name: "Traffic" 
  validates :terms_conditions,:presence => {:message => 'Accept terms and conditions'}
  before_create :update_current_theme_id

  def update_current_theme_id
    theme_id = self.original_theme_id
    theme = Theme.find(theme_id)
    theme_array = Array(theme).first.custom_appearance
    self.title = self.store_name
    self.current_theme_id = theme_id
    self.link_color = theme_array['link_color']
    self.bg_color = theme_array['bg_color']
    self.title_color = theme_array['title_color']
  end

  def traffic_count
    t = store_views.size
    t.blank? ? 0 : t
  end

  def unique_traffic_count
    t = store_views.count(:group => "ip_address")
    t.blank? ? 0 : t.size 
  end

  def total_orders
    Order.where(publisher_id: self.user_id).size
  end

  def total_sales
    Order.get_total_sales(self.user_id)
  end

  def total_conversions
    Order.where(publisher_id: self.user_id).size
  end

  def total_sales
    Order.where(publisher_id: self.user_id).sum("order_total")
  end

  %w[title description link_color bg_color title_color google_analytics].each do |key|
    attr_accessible key
    
    define_method(key) do
      custom_appearance && custom_appearance[key]
    end
  
    define_method("#{key}=") do |value|
      self.custom_appearance = (custom_appearance || {}).merge(key => value)
    end
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :is_login,:except => [:show]
  before_filter :correct_user_store,:only => [:edit,:update]
  before_filter(:only => [:show]) { load_store "store" }


  def new
    @store = Store.new
    @themes = Theme.all
  end

  #show page /stores/:number
  def show
    @products = @current_store.products
    render :layout => "custom"
  end

  #create a record for store in db /stores
  def create
    @user = current_user
    @themes = Theme.all
    @store = Store.new(params[:store])
    @store.user_id = @user.id
    @store.currency = params[:store][:currency]
    @store.store_url = root_url(:subdomain => @store.store_name != nil ? @store.store_name.split(' ').join('_').downcase : false)
    if @store.save
      track_activity @store
      flash[:notice] = "Store created successfully."
      redirect_to root_url(subdomain: @store.store_name)
    else
      flash[:error] = "Store creation failed."
      render :action => "new"
    end
  end

  #store edit form /stores/:id/edit
  def edit
    @store = Store.find(params[:id])
    @themes = Theme.all
  end

  #updating existing store record in db /stores/:id
  def update
    @store = Store.find(params[:id]) 
    @themes = Theme.all
    @store.store_url = root_url(:subdomain => params[:store][:store_name] != nil ? params[:store][:store_name].split(' ').join('_').downcase : false)
    if @store.update_attributes(params[:store])
      flash[:notice] = 'Updated successfully.'
      redirect_to edit_store_path(@store)
    else
      flash[:error] = 'Updation failed.'
      render :action => "edit"
    end
  end

  def custom_appearance_update
    @store = current_user.store
    if @store.update_attributes(params[:store])
      respond_to do |format|
        format.js
      end
    else 
      respond_to do |format|
        format.js { render "alert('Update failed')" }
      end
    end
  end

  def correct_user_store
    @store = Store.find params[:id]
    if @store.user_id != current_user.id
      flash[:error] = 'Its not your store'
      redirect_to root_path
    end
  end

  # /customise/:username?redirect_to=store sub domain or custom domain

  def customise
    username = params[:username]
    store_redirect = params[:redirect_to]
    @current_store = current_user.store
    if current_user.try(:username) != username
      flash[:error] = "Sorry you can't customise that shop!"
      redirect_to root_path
    else
      if @current_store.current_theme_id != 0 
        @theme = Theme.find(@current_store.current_theme_id).theme_content 
      else
        @theme = @current_store.custom_theme_content
      end
      render :layout => "customise"
    end
  end

  def update_theme_content
    @store = current_user.store
    @store.custom_theme_content  = params[:custom_html]
    @store.current_theme_id = 0
    if @store.save!
      respond_to do |format|
        format.json { render :json => { :success => true } }
      end
    end

  end

end

app/helpers/stores_helper.rb
module StoresHelper
	def store_user?(store)
		if signed_in?
	  		return true if store.user_id === current_user.id
	  	end
	end

	def has_store?(user)
		return true if user.store != nil
	end
end

app/views/stores/_form.html.erb
<table>
  <tr>
    <td><%= f.label :store_name,"Name" %></td>
    <td><%= f.text_field :store_name %></td>
    <td><%= validation_error(@store.errors["store_name"]) %></td>
  </tr>
  <% if controller.action_name.to_s == "new" %>
    <tr>
      <td><%= f.label :currency,"What currency do you want to sell in? <small> THis cannot be changed! </small>".html_safe %></td>
      <td><%= f.select :currency, options_for_select(CURRENCY,:selected => f.object.currency) %></td>      
    </tr>
  <% end %>

  <tr>
    <td><%= f.label "Themes" %></td>
    <td><%= collection_select :store, :original_theme_id, @themes, :id, :theme_name,{prompt: 'Please select a theme'}%></td>
  </tr>
  <tr>
    <td><%= f.label :delivery_returns,"Delivery & Returns" %></td>
    <td><%= f.text_area :delivery_returns,:cols => 30,:rows => 3 %></td>
    <td><%= validation_error(@store.errors["delivery_returns"]) %></td>
  </tr>
  <tr>
    <td><%= f.label :more_info,"More Info" %></td>
    <td><%= f.text_area :more_info,:cols => 30,:rows => 3 %></td>
    <td><%= validation_error(@store.errors["more_info"]) %></td>
  </tr>
  <tr>
    <td><%= f.label :store_terms,"Terms and Condition" %></td>
    <td><%= f.text_area :store_terms,:cols => 30,:rows => 3 %></td>
    <td><%= validation_error(@store.errors["store_terms"]) %></td>
  </tr>

  <tr>
    <td><%= f.label :payout_email,"Payout" %> <small> Which PayPal account should receive payments? </small></td>
    <td><%= f.text_field :payout_email %></td>
    <td><%= validation_error(@store.errors["payout_email"]) %></td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.check_box :show_recommendations %>&nbsp;Show my recommendations in my store</td>
     <td><%= validation_error(@store.errors["show_recommendations"]) %></td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.check_box :ask_questions %>&nbsp;Add an "Ask me anything" page to your shop.</td>
     <td><%= validation_error(@store.errors["ask_questions"]) %></td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.check_box :terms_conditions %>&nbsp;Accept tails terms and conditions</td>
     <td><%= validation_error(@store.errors["terms_conditions"]) %></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.submit @store.new_record? ? "create" : "Update"%></td>
  </tr>
</table>

app/views/stores/custom_appearance_update.js.erb
alert("OK");

app/views/stores/customise.html.erb
<!-- temp css !-->
<style type="text/css" media="screen">
body {
  font-family: "Helvetica Neue",Arial,sans-serif;
  font-size: 12px;
  line-height: 120%;
  color: #444;
  outline-width: 0;
}
a {
  color: #C1C9D1;
  text-decoration: none;
  cursor: pointer;
}
h3 {
  color: #FFF;
}
#container{
  width: 100%;
  height: 100%;
}
#drawer {
  position: absolute;
  top: 0;
  left: 0;
  width: 300px;
  bottom: 0;
  background: #3B3B3B;
  /* background-image: url('/images/customize/cardboard.png?c4da052a6b3c3970a8c67366f380148d'); */
}
#preview_container {
  position: absolute;
  top: 0;
  right: 0;
  left: 300px;
  bottom: 0;
  background-color: #FFF;
  z-index: 1000;
  -webkit-box-shadow: -3px 0 5px rgba(0, 0, 0, 0.5);
  -moz-box-shadow: -3px 0 5px rgba(0,0,0,.5);
  -ms-box-shadow: -3px 0 5px rgba(0,0,0,.5);
  -o-box-shadow: -3px 0 5px rgba(0,0,0,.5);
  box-shadow: -3px 0 5px rgba(0, 0, 0, 0.5);
}
.holder {
  width: 1200px;
  height: 100%;
}
.slider {
  width: 300px;
  height: 100%;
  position: relative;
  overflow-x: hidden;
}
.slide {
  float: left;
}

#slide-0 {
  width: 300px;
  height: 100%;

}
#slide-1 {
  width: 300px;
  height: 100%;
  
}
#slide-2 {
  width: 600px;
  height: 100%;
}
.top_toolbar {
  height: 30px;
  padding: 7px 24px 6px;
  border-bottom: 1px solid #141313;
  background-color: #252323;
  -webkit-box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.5) inset;
  -moz-box-shadow: 0 -1px 1px rgba(0,0,0,0.5) inset;
  -ms-box-shadow: 0 -1px 1px rgba(0,0,0,0.5) inset;
  -o-box-shadow: 0 -1px 1px rgba(0,0,0,0.5) inset;
  box-shadow: 0 -1px 1px rgba(0, 0, 0, 0.5) inset;
}
.content_container {
  position: absolute;
  bottom: 0;
  top: 50px;
  width: 300px;
}
#theme_list {
  position: absolute;
  bottom: 0;
  top: 10px;
  width: 286px;
  margin-top: 23px;
}
#theme_list_content {

}
.scroll_content {
  width: 250px;
  padding-right: 15px;
  padding-left: 23px;
  overflow-y: auto;
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}
#appearance_container {
  position: absolute;
  width: 100%;
  top: 44px;
  bottom: 0;
  margin-top: 0;
}
.fields {
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -ms-box-sizing: border-box;
  width: 100%;
  background-color: #FFF;
  margin-bottom: 10px;
  border-radius: 3px;
}

#editor {
  position: absolute;
  width: 600px;
  top: 44px;
  bottom: 0;
}
.label {
  color: #777;
  font-size: 12px;
  line-height: 15px;
  font-weight: bold;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.8);
  margin-right: 5px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  margin-left: 10px;
}
.field {
  padding-right: 10px;
  text-align: right;
}
.input.text_field, .select_control select {
  background-color: rgba(0, 0, 0, 0);
  vertical-align: middle;
  width: 100%;
  border-width: 0;
  text-align: right;
  margin-left: 70px;
}

</style>
<div id="container">
  <div id="drawer" stlye="width: 300px;">
    <div id="slider" class="slider">
      <div class="holder">

        <div id="slide-0" class="themes slide" style="">
          <div class="cbox" style="height:100%; width:100%;">
            <div class="top_toolbar"> 
              <div class="right" style="float:right;"> 
                <button id="use_theme_button"> Use </button>
                <button id="cancel_theme_button">Cancel</button>
              </div>
            </div>
            <div class="content_container"> 
              <div id="theme_list" class="theme_list">
                <div id="theme_list_content"  class="scroll_content" style="position: absolute; top: 0px; bottom: 0px;">
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div>
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div> 
                  <div class="theme">
                    <img width="250px" height="200px" src="http://media.tumblr.com/themes/wide/HQnVbyhKLX1hflMj.png">   
                    <p style="color:#FFF"> Theme <span> by  <a href="#" target="_blank">Tommy</a></span></p>
                  </div>     
                </div>       
              </div>
            </div>
          </div>
        </div>

        <div id="slide-1" class="appearance slide">
          <div class="top_toolbar"> 
              <div class="left"style="float:left">
                  <button id="back_to_themes_button" class="dark_button back_button" slide="0"><span></span>Themes</button>
              </div>
              <div class="right" style="float:right">
                  <button id="close_button" class="medium_button">Exit</button>
              </div>
          </div>
          <div id="appearance_container" class="content_container" style="background: #3B3B3B;"> 
            <div class="apperance_content scroll_content" style="position: absolute; top: 20px; bottom: 0px;">

              <div id="current_theme_view_anchor">
                    <div id="current_theme_view" class="first_module">
                        <div class="theme_thumbnail selected">
                          <img id="current_theme_thumbnail" width="250px" class="thumbnail_image_media shadow" 
                          src="http://www.tumblr.com/images/customize/theme_thumbnail_custom.png">
                        </div>

                        <div class="right" style="float:right;">
                            <button id="edit_html_button" class="dark_button inset_button edit_html" slide="2" style="">Edit HTML</button>
                        </div>
                        
                        <p style="color:#FFF">
                            <span id="" class="">Custom theme</span>
                            <br>
                        </p>
                    </div>
              </div>
              <hr>
              <%= form_for @current_store, :url => update_custom_appearance_path(params[:store]),:method => 'PUT', remote: true do |f| %>

                <div id="shop_header_view" class="fields"> 

                  <label for="title" class="text_field_control">
                      <span class="label"><%= f.label :title %> </span> 
                      <span class="field"><%= f.text_field :title%></span>
                      <span class="label"><%= f.label :description %> </span> 
                      <span class="field"><%= f.text_area :description, rows:"5", cols: "30"%></span>
                  </label>
                  <!-- Background [upload] [clear] !-->
                  <!-- Header [upload] [clear] !-->
                </div>


                <div id="appearance_view">
                <h3> Appearance </h3>
                <div class="fields">
                  <label for="link_color" class="text_field_control">
                    <span class="label"><%= f.label :link_color, "Link Color" %></span> 
                    <span class="field">
                      <div class="color_swatch" style="background-color: #708090; border-color: #708090">
                        <%= f.text_field :link_color, class: "text_field color" %>
                      </div>
                    </span>
                  </label>

                  <label for="bg_color" class="text_field_control">
                    <span class="label"><%= f.label :bg_color, "Background Color" %> </span> 
                    <span class="field">
                      <div class="color_swatch" style="background-color: #708090; border-color: #708090">
                        <%= f.text_field :bg_color, class: "text_field color" %>
                      </div>
                    </span>
                  </label>

                  <label for="title_color" class="text_field_control">
                    <span class="label"><%= f.label :title_color, "Title Color" %></span> 
                    <span class="field">
                      <div class="color_swatch" style="background-color: #708090; border-color: #708090">
                        <%= f.text_field :title_color, class: "text_field color" %>
                      </div>
                    </span>
                  </label>

                </div>
                <a class="reset_button"> Reset Defaults </a>
              </div>

              <div id="advanced_container">
                <h3> Advanced </h3>
                <div class="fields">
                    <label for="google_analytics_id" class="text_field_control">
                      <span class="label"><%= f.label :google_analytics, "Google Analytics ID" %></span> 
                      <span class="field"><%= f.text_field :google_analytics %></span>
                    </label>
                </div>

              </div>
              <%= f.submit "Save" %>

            <% end %>


              

             </div>

          </div>
        </div>

        <div id="slide-2" class="editor slide">
          <div class="top_toolbar"> 
              <div class="left" style="float:left;">
                  <button id="back_to_appearance_button" class="dark_button back_button" slide="1"><span></span>Appearance</button>
              </div>
              <div class="right" style="float:right;">
                  <button id="save_preview_button" style="display:none" class="green_button inset_button">Save</button>
                  <button id="update_preview_button" class="green_button" title="⌘S">Update Preview</button>
              </div>

          </div>

          <div id="editor" class="ace_tail ace_editor">
            <%= @theme %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="preview_container" style="left:300px;">
    <iframe frameborder="0" src="http://assets.txmblr.com/customize_preview_receiver.html?07f634b04eeac3f5e009c8b812a54538" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; display: block;"></iframe>
      
  </div>
  <input id="current_store_id" type="hidden" value="<%= @current_store.id %>"/>
  <input id="current_username" type="hidden" value="<%= @current_user.username %>"/>
</div>  

app/views/stores/edit.html.erb
<div class="row">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="large-9 columns">
  	<hr>
  	<h3> Things to do here.</h3>
  	<hr>
    <%= form_for @store, :html => {:class => "message"},:method => 'PUT' do |f| %>
      <%= render :partial => "form",:locals => {:f => f} %>
    <% end %>
  </div>
</div>

app/views/stores/index.html.erb
<h4> Current user's products page-> <small> Work in progress...</small></h4> 
<d iv id="store_products">
  <div id="products" style="margin-top: 31px;">
    <%= link_to "<div style='font-size: 52px;'>+</div><br/>Add a Product".html_safe,"javascript:void(0)",:id => "product_create" %>
  </div>
  <br><hr>
  <% if @products %>
    <% @products.each do |product| %>
      <div id="products">
        <% @cover_photo = FileHandler.where(:product_id => product.id,:is_cover => true).first %>
        <%= @cover_photo != nil ? image_tag(@cover_photo.file_path.thumb) : '' %>
        <%= product.product_title %>
        <%= link_to "Edit", edit_product_path(:number => product.random_no) %>
        <%= link_to "Show", product_path(:number => product.random_no) %>
      </div><br><hr>
    <% end %>
  <% end %>
</div>

app/views/stores/new.html.erb
<div class="wrapper clearfix">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="grid_9">
    <%= form_for @store,:url =>stores_path(@store),:html => {:class => "message"} do |f| %>
      <%= render :partial => "form",:locals => {:f => f} %>
    <% end %>
  </div>
</div>