config/routes.rb
require 'sidekiq/web'
Aries::Application.routes.draw do

  constraints(Subdomain) do
    match '/' => 'stores#show'
    post '/orders' => 'orders#create'
    post '/requests' => 'requests#create'
    match "/:number" => "products#show",:as => "product"
  end
  
  mount Sidekiq::Web, at: "/sidekiq"

  root :to => "home#index"
  
  
  resources :file_handlers
  resources :orders do
    resources :comments,:only => [:new,:create,:show] 
  end
  
  
  resources :home do
    collection do
      get :subscriptions
      get :stories
      get :recommendations
    end
  end
  
  get '/find_friends', to: 'settings#find_friends', as: :find_friends

  get "new/create"

  get "new/destroy"
  get 'tags/:tag', to: 'products#index', as: :tag
  get '/notifications', to: 'settings#user_notifications', as: :notifications
  devise_for :users

  match "auth/:provider/callback" => "social_sites#create"
  
  resources :user_registrations,:only => [:new,:create] do
    collection do
      get :confirm_account
      put :resend_confirmations
    end
  end
  
  resources :dashboard do
    collection do
      get :products 
      get :orders
      get :views
      get :reviews
    end
  end
  
  resources :settings,:except => [:new,:create,:show,:edit,:update,:index,:destroy],:path => '/dashboard/settings/' do
    member do
      get :notifications
      post :create_notification
      get :edit_notifications
      put :notification_updation
    end
    collection do
      get :account
      put :update_account
      get :social
      post :send_twitter_message
      get :complete_social_signup
      put :update_social_signup
    end
  end
  resources :stores, :except =>[:show]
  resources :products,:except => [:show,:edit,:update] do
    member do
      get :payment
      put :recommend
      put :post_product
    end
    
    collection do
      get :top_products
      put :product_delete
    end
  end

  resources :profiles, :except => [:show] do
    collection do
      get :balance
      get :shopping
      get :referral
    end
    member do
      get :subscriptions, :subscribers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :requests, only: [:index]
  resources :activities, only: [:index]
  resources :questions, except: [:new, :edit] do
    collection do
      get :answered
      get :your_questions
    end
    resources :answers, only: [:new,:create]
  end
  resources :themes
  
  match "/discover" => "discover#discover"
  match "/discover/products" => "discover#product"
  match "/discover/shops" => "discover#shop"
  match "/discover/people" => "discover#people"
  match "/discover/tags" => "discover#tags"
  match "/products/add" => "products#add", :as => "add_product"
  match "/listing/:id" => "products#listing_complete", :as => "listing"
  match "customise/:username" => "stores#customise"
  match 'products/:product_id/make_payment' => 'products#make_payment', :as => :confirm_payment
  match "/products/:number/edit" => "products#edit",:as => "edit_product"
  match "/products/:number" => "products#update",:as => "update_product"
  match "/products/:random_no/download_product" => 'products#download_product',:as => 'download'
  match "profiles/:username" => "profiles#show"
  match "profiles/:username/drawer" => "profiles#drawer", :as => "drawer"
  match "profiles/:username/recommendations" => "profiles#recommends", :as => "recommends"
  match "profiles/:username/activities" => "profiles#activities", :as => "activities"
  match "stores/update_theme_content" => "stores#update_theme_content"
  match "/update_custom_appearance" => "stores#custom_appearance_update"
  post  "/shipping_option", to: "stores#add_shipping_profiles"

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_trends
  respond_to :html,:json

  #home page /
  def index
    if signed_in?
      #######Important######
      #@who_to_subscribe_to = current_user.who_to_subscibe_to.limit(5)
      ###################
      if Product.first != nil
        #@top_ids,@p_ids = Product.top_products(20,'')
        #@products = Product.featured_products.where("products.id IN (#{@p_ids.empty? ? '0' : @p_ids.split(",").join(",")})").joins("JOIN (VALUES #{@top_ids.join(",")}) as x (id, ordering) ON products.id = x.id").order('x.ordering').group("x.ordering")
        @products = Product.all

      else
        @products = []
      end
      respond_with @products do |format|
        format.json
        format.html
      end
    else
      render 'signed_out_index'
    end
  end
  
  #only products from people you've subscribe to /home/subscriptions
  def subscriptions
    ids = []
    subscribers = current_user.subscriptions 
    subscribers.each do |sub|
      user = User.find(sub.id)
      ids<< (user.store != nil ? user.store.id : '0')
    end
    @products = Product.featured_products.where("store_id IN (#{ids.empty? ? '0' : ids.split(",").join(",")})")
    respond_with @products do |format|
      format.json
      format.html { render action:'index'}
    end
    #render :action => :index
  end
  
  
  #Currently featured products from sellers on the site /home/featured
  def stories
    @stories = Activity.from_your_social_circle(current_user).includes(:user,:trackable)
    puts @stories.count
    respond_with @stories do |format|
      format.json
      format.html { render action:'index'}
    end
  end
  
  # Only products recommendaations from people in your circle /home/recommendations
  #Recommend feature will not be in the site's alpha version..
  def recommendations
    @uids = []
    @ids = []
    current_user.friends.each do |friend|
      @uids<< ("'#{friend.uid}'")
    end
    current_user.relationships.each do |sub|
      @ids<< (sub.publisher_id)
    end
    @users = User.where("provider_id IN (#{@uids.empty? ? "'0'" : @uids.split(",").join(",")})")
    @users.each do |user|
      @ids<< (user.id)
    end
    @recommendations = Recommendation.recommended_products(@ids)
    respond_with @recommendations do |format|
      format.json
      format.html { render action:'index'}
    end
  end
  
private 
  def set_trends
    #call my trend algo from here
    @tags = Tag.limit(6)
    @trends = Trend.get(6) # Just here for testing purposes
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home_top_nav.html.erb
  <% if current_user and current_user.account_activation_code != nil %> 
    <div class="confirm_account">We sent an email with instructions about how to confirm your account,please check your email or <%= link_to 'resend email',resend_confirmations_user_registrations_path,:method => 'PUT' %></div>
  <% end %>
  
  <div class="section-container horizontal-nav" data-section="horizontal-nav">
    <section class="section">
      <p class="title"> <%= link_to "Featured","/" %> </p>
    </section>
    <section class="section">
      <p class="title"> <%= link_to "Stories","/home/stories" %> </p>
    </section>
    <section class="section">
      <p class="title"> <%= link_to "Subscriptions","/home/subscriptions" %> </p>
    </section>
    <!--
    <section class="section">
      <p class="title"> <%#link_to "Recommendations","/home/recommendations" %> </p>
    </section>
    !-->

  </div>

app/views/home/_index.html.erb
<ul>
<% for product in @products %>
  <li style="list-style-type: none;">
  	<%#product.full_name %> <%= product.store.user.full_name %>
  	has posted a product <%= product.product_title %> on <%= product.created_at.strftime("%b %d %Y") %>
  </li>    
<% end %>
</ul>

app/views/home/_recommendations.html.erb
<ul>
<% for product in @recommendations %>
  <li style="list-style-type: none;"><%= product.full_name %> has recommended a product <%= product.product_title %> on <%= product.created_at.strftime("%b %d %Y") %></li>    
<% end %>
</ul>

app/views/home/_stories.html.erb
<% if @stories %>
	<%= render partial: 'activities/activity', collection: @stories %>
<% else %>
	<h4> They are currently no stories present.</h4>
<% end %>
<hr>

<!--
	 @uids = []
-    @ids = []
-    @stories = []
-    @store_ids = []
-    current_user.friends.each do |friend|
-      @uids<< ("'#{friend.uid}'")
-    end
-    current_user.relationships.each do |sub|
-      @ids<< (sub.publisher_id)
-      @store_ids<< (User.find(sub.publisher_id).store != nil ? User.find(sub.publisher_id).store.id : '0')
-    end
-    @users = User.where("provider_id IN (#{@uids.empty? ? "'0'" : @uids.split(",").join(",")})")
-    @users.each do |user|
-      @ids<< (user.id)
-      @store_ids<< (user.store.id)
-    end
-    @recommendations = Recommendation.includes(:user).includes(:product).where("user_id IN (#{@ids.empty? ? '0' : @ids.split(",").join(",")})")
-    @orders = Order.includes(:product).where("user_id IN (#{@ids.empty? ? '0' : @ids.split(",").join(",")})")
-    @products = Rails.cache.fetch('products', :expires_in => 24.hours) {Product.includes(:store).where("store_id IN (#{@store_ids.empty? ? '0' : @store_ids.split(",").join(",")})")}
-    @recommendations.each do |recommend|
-      @stories<<[recommend.user.full_name,"recommended a product",recommend.product.product_title]
-    end
-    @orders.each do |order|
-      @stories<<[order.full_name,"bought a product",order.product.product_title]
-    end
-    @products.each do |product|
-      @stories<<[product.store.user.full_name,"listed a product",product.product_title]
-    end
!-->

app/views/home/_subscriptions.html.erb
<ul>
<% for product in @products %>
  <li style="list-style-type: none;"><%= product.full_name %> has posted a product <%= product.product_title %> on <%= product.created_at.strftime("%b %d %Y") %></li>    
<% end %>
</ul>

app/views/home/_tags.html.erb
<ul class="side-nav">
	<% @tags.each do |tag| %>
		<li><%= link_to tag.name, "#" %></li>
	<% end %>
</ul>
<%= @trends.inspect if @trends %>

app/views/home/index.html.erb
<div class="row">
	<% action = controller.action_name.to_s %>
	<div class="large-9 small-12 columns">	
		<%= render "home_top_nav" %>
		<div id = "main-area">
			<% if action == "index"> %>
				<%= render "index" %>
			<% else %>
				<%= render "/home/#{action}" %>
			<% end %>
		</div>
	</div>
	<div id = "side-bar" class="large-3 small-12 columns">
		<%#= render "tags" %>
	</div>

	
</div>

app/views/home/signed_out_index.html.erb
<div class="mid-content text-center">
  <h1> Rewiring e-commerce around people.</h1>
  <!-- <p>  Enabling a socially engaging and rewarding commerce experience for both buyers and sellers.</p> !-->
</div>
<h2>Enabling a socially engaging and rewarding commerce experience for both buyers and sellers. </h2>

<div class="text">
  <span class="dark">Lorem ipsum dolor echo park raw denim brunch cliche viral irony williamsburg. Sustainable cosby sweater high life brooklyn. Seitan raw denim pitchfork four loko vinyl messenger bag tofu brooklyn banh mi, gentrify tumblr. Brunch cliche 8-bit williamsburg dreamcatcher, hoodie art party. Biodiesel gluten-free twee mlkshk. Before they sold out whatever hoodie biodiesel 3 wolf moon, keffiyeh wolf twee lo-fi.
    <br><br>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
</div>