config/routes.rb
require 'sidekiq/web'
Aries::Application.routes.draw do

  constraints(Subdomain) do
    match '/' => 'stores#show'
    post '/orders' => 'orders#create'
    post '/requests' => 'requests#create'
    match "/:number" => "products#show",:as => "product"
  end
  
  mount Sidekiq::Web, at: "/sidekiq"

  root :to => "home#index"
  
  
  resources :file_handlers
  resources :orders do
    resources :comments,:only => [:new,:create,:show] 
  end
  
  
  resources :home do
    collection do
      get :subscriptions
      get :stories
      get :recommendations
    end
  end
  
  get '/find_friends', to: 'settings#find_friends', as: :find_friends

  get "new/create"

  get "new/destroy"
  get 'tags/:tag', to: 'products#index', as: :tag
  get '/notifications', to: 'settings#user_notifications', as: :notifications
  devise_for :users

  match "auth/:provider/callback" => "social_sites#create"
  
  resources :user_registrations,:only => [:new,:create] do
    collection do
      get :confirm_account
      put :resend_confirmations
    end
  end
  
  resources :dashboard do
    collection do
      get :products 
      get :orders
      get :views
      get :reviews
    end
  end
  
  resources :settings,:except => [:new,:create,:show,:edit,:update,:index,:destroy],:path => '/dashboard/settings/' do
    member do
      get :notifications
      post :create_notification
      get :edit_notifications
      put :notification_updation
    end
    collection do
      get :account
      put :update_account
      get :social
      post :send_twitter_message
      get :complete_social_signup
      put :update_social_signup
    end
  end
  resources :stores, :except =>[:show]
  resources :products,:except => [:show,:edit,:update] do
    member do
      get :payment
      put :recommend
      put :post_product
    end
    
    collection do
      get :top_products
      put :product_delete
    end
  end

  resources :profiles, :except => [:show] do
    collection do
      get :balance
      get :shopping
      get :referral
    end
    member do
      get :subscriptions, :subscribers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :requests, only: [:index]
  resources :activities, only: [:index]
  resources :questions, except: [:new, :edit] do
    collection do
      get :answered
      get :your_questions
    end
    resources :answers, only: [:new,:create]
  end
  resources :themes
  
  match "/discover" => "discover#discover"
  match "/discover/products" => "discover#product"
  match "/discover/shops" => "discover#shop"
  match "/discover/people" => "discover#people"
  match "/discover/tags" => "discover#tags"
  match "/products/add" => "products#add", :as => "add_product"
  match "/listing/:id" => "products#listing_complete", :as => "listing"
  match "customise/:username" => "stores#customise"
  match 'products/:product_id/make_payment' => 'products#make_payment', :as => :confirm_payment
  match "/products/:number/edit" => "products#edit",:as => "edit_product"
  match "/products/:number" => "products#update",:as => "update_product"
  match "/products/:random_no/download_product" => 'products#download_product',:as => 'download'
  match "profiles/:username" => "profiles#show"
  match "profiles/:username/drawer" => "profiles#drawer", :as => "drawer"
  match "profiles/:username/recommendations" => "profiles#recommends", :as => "recommends"
  match "profiles/:username/activities" => "profiles#activities", :as => "activities"
  match "stores/update_theme_content" => "stores#update_theme_content"
  match "/update_custom_appearance" => "stores#custom_appearance_update"
  post  "/shipping_option", to: "stores#add_shipping_profiles"

  

end

app/controllers/settings_controller.rb
require "twitter"
class SettingsController < ApplicationController
  before_filter :is_login
  def account
    @user = current_user
  end
  
  #update user record /accounts/:id
  def update_account
    @user = current_user
    @user.errors.add(:current_password,'is required') if (!params[:user][:password].to_s.blank? and  params[:user][:current_password].to_s.blank?)
    if params[:user][:password].to_s.blank?
      if @user.update_without_password(params[:user])
        flash[:notice] = 'Updated successfully.'
        redirect_to account_settings_path
      else
        flash[:error] = 'Updation failed'
        render :action => 'account'
      end
    else
      if @user.errors.empty? and @user.update_with_password(params[:user])
        sign_in(@user, :bypass => true)
        flash[:notice] = 'Updated successfully.'
        redirect_to account_settings_path
      else
        flash[:error] = 'Updation failed'
        render :action => 'account'
      end
    end
  end
  
  #complete social signup /accounts/complete_social_signup
  def complete_social_signup
    #    render :layout => false
  end
  
  #updating username and password after sign up with social accounts
  def update_social_signup
    @user = current_user
    if current_user.provider != 'twitter'
      if !params[:user][:password].to_s.blank?
        @user.update_attributes(params[:user])
      else
        @user.username = params[:user][:username]
        @user.save
      end
    else
      @user.attributes = params[:user]
      @user.save(:validate => false)
    end
    sign_in(:user, @user, :bypass => true)
    redirect_to account_settings_path
  end
  
  #connecting to social site accounts/social_connect
  def social
    if current_user.provider != nil
      if current_user.provider == 'facebook'
        @f_connected = 'facebook'
        if current_user.social_connections.exists?
          @t_connected = 'twitter'
        else
          @t_connected = nil
        end
      else
        @t_connected = 'twitter'
        if current_user.social_connections.exists?
          @f_connected = 'facebook'
        else
          @f_connected = nil
        end
      end
    elsif current_user.social_connections.exists?
      @f_connected = current_user.social_connections.where("provider = 'facebook'").exists? ? 'facebook' : nil
      @t_connected = current_user.social_connections.where("provider = 'twitter'").exists? ? 'twitter' : nil
    else
      @f_connected = nil
      @t_connected = nil
    end
  end
  
  def find_friends
    social
    fetch_fb_friends
    if params[:fb_id]
      Friend.create(:user_id => current_user.id,:uid => params[:fb_id],:provider => 'facebook') if !Friend.exists?(:user_id => current_user.id,:uid => params[:fb_id])
    end
    twitter
  end
  
  def twitter
    @twi_friends = []
    if (current_user.provider != nil and current_user.provider == 'twitter') or current_user.social_connections.where("provider = 'twitter'").exists?
      fetch_tw_friends
    end
    #    Twitter.direct_message_create('kapil517', 'good1')
  end
  
  def send_twitter_message
    fetch_tw_friends
    Twitter.direct_message_create("#{params[:username]}", "#{params[:text]}")
    Friend.create(:user_id => current_user.id,:uid => params[:twitter_id],:provider => 'twitter') if !Friend.exists?(:user_id => current_user.id,:uid => params[:twitter_id])
    flash[:notice] = 'Message sent'
    redirect_to '/find_friends'
  end
  
  def user_notifications
    @notifications = current_user.notifications(current_user)
  end
  
  #notifications page /accounts/:id/notifications
  def notifications
    @user = current_user
    @notification = Notification.new
  end

  #create notifications /accounts/:id/create_notifications
  def create_notification
    @notification = current_user.build_notification(params[:notification])
    @notification.save
    redirect_to edit_notifications_setting_path(@notification)
  end

  #edit notification /accounts/:id/edit_notifications
  def edit_notifications
    @user = current_user
    @notification = Notification.find(params[:id])
  end

  #update notification /accounts/:id/notification_updation
  def notification_updation
    @user = current_user
    @notification = Notification.find(params[:id])
    @notification.update_attributes(params[:notification])
    redirect_to edit_notifications_setting_path(@notification)
  end
  private
  def fetch_fb_friends
    @fb_friends = []
    if current_user.provider != nil and current_user.provider == 'facebook'
      @fb_friends = FbGraph::User.new('me', :access_token => current_user.token).fetch.friends
    elsif current_user.social_connections.where("provider = 'facebook'").exists?
      @fb_friends = FbGraph::User.new('me', :access_token => current_user.social_connections.where("provider = 'facebook'").first.token).fetch.friends
    end
  end
  
  def fetch_tw_friends
    PostToTwitter.twitter_configuration(current_user)
    client = Twitter::Client.new
    @twi_friends = client.friends.all
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_friends.html.erb
<ul class="socialNetworks">
  <li style="list-style-type: none;">
    <%= @f_connected == 'facebook' ? '' : (link_to 'Facebook','/auth/facebook') %>
  </li>
  <li style="list-style-type: none;">
    <%= @t_connected == 'twitter' ? '' : (link_to 'Twitter','/auth/twitter') %>
  </li>
</ul>

app/views/settings/_notifications.html.erb
<table>
  <tr>
    <td>Email Notifications</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_subscribe_to_you %> When someone subscribes to you</td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_comments_on_your_story %> When someone comments on your story </td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_product_is_featured %> When your product is featured </td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_recommends_your_product %> When someone recommends one of your products</td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_purchase_your_product %>When someone purchase one of your products</td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :email_request_sold_out_product %> When someone requests your sold out products </td>
  </tr>


  <tr>
    <td>Updates</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :news %>News</td>
  </tr>
  <tr>
    <td></td>
    <td><%= f.check_box :tips %>Tips</td>
  </tr>

  <tr>
    <td></td>
    <td><%= f.submit "Save Changes" %></td>
  </tr>
</table>

app/views/settings/account.html.erb
<div class="row">
  <%= render :partial => "dashboard/side_tabs" %>
  <div class="large-9 columns">
    <div class="avatar_div" style="height: 240px; width: 240px;"> 
      <img style="height: 240px; width: 240px;" src="<%= @user.avatar("thumb_big") %>"/> 
      <div class="modal"></div> 
    </div>
    <br>
    <%= render partial: "file_handlers/avatar" %>
    <hr>
    <%= form_for @user,:url =>update_account_settings_path,:html => {:class => "message"},:method => 'PUT' do |f| %>
      <%= f.hidden_field :status,:value => 'update' %>
      <table>
        <tr>
          <td><%= f.label :email,"Email" %></td>
          <td><%= f.text_field :email %></td>
          <td><%= validation_error(@user.errors["email"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :first_name,"First Name" %></td>
          <td><%= f.text_field :first_name %></td>
          <td><%= validation_error(@user.errors["first_name"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :last_name,"Last Name" %></td>
          <td><%= f.text_field :last_name,:id => "last_name" %></td>
          <td><%= validation_error(@user.errors["last_name"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :username,"User Name" %></td>
          <td><%= f.text_field :username %></td>
          <td><%= validation_error(@user.errors["username"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :bio,"Your story" %></td>
          <td><%= f.text_area :bio,:cols => 30,:rows => 3 %></td>
          <td><%= validation_error(@user.errors["bio"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :location,"Location" %></td>
          <td><%= f.text_field :location %></td>
          <td><%= validation_error(@user.errors["location"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :gender,"Gender" %></td>
          <td><%= f.radio_button :gender,"male",:checked => true %><%= "Male" %><%= f.radio_button :gender,"female" %><%= "Female" %><%= f.radio_button :gender,"unspecified" %><%= "Unspecified" %></td>
        </tr>
        <tr>
          <td><%= f.label :website,"Website" %></td>
          <td><%= f.text_field :website %></td>
          <td><%= validation_error(@user.errors["website"]) %></td>
        </tr>
  
        <tr>
          <td><%= f.label :country,"Country" %></td>
          <td><%= f.text_field :country %></td>
          <td><%= validation_error(@user.errors["country"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :timezone,"Timezone" %></td>
          <td><%= f.time_zone_select :timezone %></td>
          <td><%= validation_error(@user.errors["timezone"]) %></td>
        </tr>
        <tr>
          <td><%= f.label :current_password,"Current Password" %></td>
          <td><%= f.password_field :current_password %></td>
          <td><%= validation_error(@user.errors['current_password']) %></td>
        </tr>
        <tr>
          <td><%= f.label :password,"New Password" %></td>
          <td><%= f.password_field :password %></td>
          <td><%= validation_error(@user.errors['password']) %></td>
        </tr>
        <tr>
          <td><%= f.label :password_confirmation,"Confirm Password" %></td>
          <td><%= f.password_field :password_confirmation %></td>
          <td><%= validation_error(@user.errors['password_confirmation']) %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Update" %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/settings/complete_social_signup.html.erb
<div id="page-wrap">

  <div id="contact-area">

    <%= form_for current_user,:url =>update_social_signup_settings_path,:html => {:class => "message",:method => 'PUT'} do |f| %>
      <table>
        <tr>
          <td><%= f.label :username,"User Name:" %></td>
          <td><%= f.text_field :username ,:id=>"Name"%></td>
        </tr>
        <tr>
          <td><%= f.label :email,"Email:" %></td>
          <td><%= current_user.email %></td>
        </tr>
        <tr>
          <td><%= f.label :password,"Password:" %></td>
          <td><%= f.password_field :password,:id=>"Name" %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "Save",:class=>"submit-button"  %></td>
        </tr>
      </table>
      <div style="clear: both;"></div>
    <% end %>
  </div>

</div>

<style>

  #page-wrap {
    width: 660px;
    background: white;
    padding: 20px 50px 20px 50px;
    margin: 20px auto;
    min-height: 500px;
    height: auto !important;
    height: 500px;
  }
  
  #header,#footer{
    display:none;
  }

  #contact-area {
    width: 600px;
    margin-top: 25px;
  }

  #contact-area input {
    padding: 5px;
    width: 300px;
    font-family: Helvetica, sans-serif;
    font-size: 1.4em;
    margin: 0px 0px 10px 0px;
    border: 2px solid #ccc;
  }

  #contact-area input.submit-button {
    width: 100px;
    float: right;
  }

</style>

app/views/settings/edit_notifications.html.erb
<div class="row">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="large-9 columns">
    <%= form_for @notification, :url => notification_updation_setting_path(@notification),:html => {:class => "message"} do |f|%>
      <%= render :partial => "notifications",:locals => {:f => f} %>
    <% end %>
  </div>
</div>

app/views/settings/find_friends.html.erb
<div class="wrapper clearfix" style="width:1030px;">
  <%= render :partial => "dashboard/side_tabs" %>
  <div>
    <div class="grid_9" style="float:left;width:320px;">
      <%= render :partial => "friends" %>
      <table>
        <% @twi_friends.each do |tw_friend| %>
          <tr>
            <td><%= image_tag(tw_friend.profile_image_url) %><%= tw_friend.name %>&nbsp;&nbsp;<%= (User.exists?(:provider_id => tw_friend.id,:provider => 'twitter') or SocialConnection.exists?(:provider_id => tw_friend.id,:provider => 'twitter')) ? '(subscribed)' : (link_to_function 'Invite',"openOffersDialog('#{tw_friend.username}','#{tw_friend.id}')") %></td>
          </tr>
        <% end %>
      </table>

      <div id="overlay" class="overlay" style="display: none;"></div>
      <div id="boxpopup" class="box" style="display: none;">
        <a onclick="closeOffersDialog('boxpopup');" class="boxclose"></a>
        <div id="content">
          <%= form_tag send_twitter_message_settings_path do %>
            <%= hidden_field_tag "twitter_id" %>
            <%= text_field_tag "username",'',:readonly => true %>
            <%= text_area_tag "text",'',:rows => '4',:cols => '30' %>
            <%= submit_tag 'Send' %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Share with your friends -->
    <div class="span8" style="width:390px;position:relative;top:22px;float:left;">
      <% unless @fb_friends.empty? %>
        <section class="facebook-box">
          <div class="frame">
            <div class="search-box">
              <input type="text" id="fr_search" value="" placeholder="search facebook friends" />
            </div>
            <div>
              <table width="35%;" cellspacing="0" cellpadding="5%;" id="friends-table" style="display:none;">
                <% for friend in @fb_friends %>
                  <tr>
                    <td><%= image_tag(friend.picture,:width => '50',:height => '50') %></td>
                    <td><%= friend.name %>&nbsp;&nbsp;<%= (User.exists?(:provider_id => friend.identifier,:provider => 'facebook') or SocialConnection.exists?(:provider_id => friend.identifier,:provider => 'facebook')) ? '(subscribed)' : (link_to_function 'Invite',"invite_fb_friends('#{friend.identifier}')") %></td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>

<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script>

        FB.init({
          appId: <%= FB_APP_ID %>,
          frictionlessRequests: true
        });

        function invite_fb_friends(uid) {
          sendRequestToRecipients(uid)
        }


        function sendRequestToRecipients(uid) {
          FB.ui({method: 'send',
            link: 'http://casppa.herokuapp.com/',
            to: [uid]
          }, function(response) {
            window.location.href = "/find_friends?fb_id=" + uid;
          });
        }
</script>

app/views/settings/notifications.html.erb
<div class="row">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="large-9 columns">
    <%= form_for @notification, :url => create_notification_setting_path(@user,@notification),:html => {:class => "message"} do |f|%>
      <%= render :partial => "notifications",:locals => {:f => f} %>
    <% end %>
  </div>
</div>

app/views/settings/social.html.erb
<div class="row">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="large-9 columns">
    <table>
      <tr>
        <td>Facebook</td>
        <td>
          <div class="Facebook">
            <input type="checkbox" value="facebook" id="Facebook" class="<%= @f_connected == 'facebook' ?  '' : 'facebook'%>" name="check" <%= @f_connected == 'facebook' ?  'checked disabled' : ''%> />
            <label for="Facebook"></label>
          </div>
        </td>
      </tr>
      <tr>
        <td>Twitter</td>
        <td>
          <div class="Twitter">
            <input type="checkbox" value="twitter" id="Twitter" class="<%= @t_connected == 'twitter' ?  '' : 'twitter'%>" name="check" <%= @t_connected == 'twitter' ?  'checked disabled' : ''%>/>
            <label for="Twitter"></label>
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>


<script>
  $("input.facebook").click(function() {
    $(this).attr("disabled", true);
    window.location.href = "/auth/facebook"
  });

  $("input.twitter").click(function() {
    $(this).attr("disabled", true);
    window.location.href = "/auth/twitter"
  });
</script>

app/views/settings/user_notifications.html.erb
<div class="wrapper clearfix">
  <%= render :partial => "dashboard/side_tabs" %>

  <div class="grid_9">
    <ul class="notifications">
      <% for notification in @notifications %>
        <li><%= notification[2] %></li>    
      <% end %>
    </ul>
  </div>
</div>