config/routes.rb
require 'sidekiq/web'
Aries::Application.routes.draw do

  constraints(Subdomain) do
    match '/' => 'stores#show'
    post '/orders' => 'orders#create'
    post '/requests' => 'requests#create'
    match "/:number" => "products#show",:as => "product"
  end
  
  mount Sidekiq::Web, at: "/sidekiq"

  root :to => "home#index"
  
  
  resources :file_handlers
  resources :orders do
    resources :comments,:only => [:new,:create,:show] 
  end
  
  
  resources :home do
    collection do
      get :subscriptions
      get :stories
      get :recommendations
    end
  end
  
  get '/find_friends', to: 'settings#find_friends', as: :find_friends

  get "new/create"

  get "new/destroy"
  get 'tags/:tag', to: 'products#index', as: :tag
  get '/notifications', to: 'settings#user_notifications', as: :notifications
  devise_for :users

  match "auth/:provider/callback" => "social_sites#create"
  
  resources :user_registrations,:only => [:new,:create] do
    collection do
      get :confirm_account
      put :resend_confirmations
    end
  end
  
  resources :dashboard do
    collection do
      get :products 
      get :orders
      get :views
      get :reviews
    end
  end
  
  resources :settings,:except => [:new,:create,:show,:edit,:update,:index,:destroy],:path => '/dashboard/settings/' do
    member do
      get :notifications
      post :create_notification
      get :edit_notifications
      put :notification_updation
    end
    collection do
      get :account
      put :update_account
      get :social
      post :send_twitter_message
      get :complete_social_signup
      put :update_social_signup
    end
  end
  resources :stores, :except =>[:show]
  resources :products,:except => [:show,:edit,:update] do
    member do
      get :payment
      put :recommend
      put :post_product
    end
    
    collection do
      get :top_products
      put :product_delete
    end
  end

  resources :profiles, :except => [:show] do
    collection do
      get :balance
      get :shopping
      get :referral
    end
    member do
      get :subscriptions, :subscribers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :requests, only: [:index]
  resources :activities, only: [:index]
  resources :questions, except: [:new, :edit] do
    collection do
      get :answered
      get :your_questions
    end
    resources :answers, only: [:new,:create]
  end
  resources :themes
  
  match "/discover" => "discover#discover"
  match "/discover/products" => "discover#product"
  match "/discover/shops" => "discover#shop"
  match "/discover/people" => "discover#people"
  match "/discover/tags" => "discover#tags"
  match "/products/add" => "products#add", :as => "add_product"
  match "/listing/:id" => "products#listing_complete", :as => "listing"
  match "customise/:username" => "stores#customise"
  match 'products/:product_id/make_payment' => 'products#make_payment', :as => :confirm_payment
  match "/products/:number/edit" => "products#edit",:as => "edit_product"
  match "/products/:number" => "products#update",:as => "update_product"
  match "/products/:random_no/download_product" => 'products#download_product',:as => 'download'
  match "profiles/:username" => "profiles#show"
  match "profiles/:username/drawer" => "profiles#drawer", :as => "drawer"
  match "profiles/:username/recommendations" => "profiles#recommends", :as => "recommends"
  match "profiles/:username/activities" => "profiles#activities", :as => "activities"
  match "stores/update_theme_content" => "stores#update_theme_content"
  match "/update_custom_appearance" => "stores#custom_appearance_update"
  post  "/shipping_option", to: "stores#add_shipping_profiles"

  

end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController
	before_filter :set_trends, except: :tags
	respond_to :html,:js, :except => :tags
	helper_method :cat_type

	def discover
		@categories = (cat_type == "all") ? ProductCategory.all : ProductCategory.where(category_type: cat_type)
		#Top product method needs to be used here also.
		@products = (cat_type == "all") ? Product.all : Product.where(product_type: cat_type)
	end

	def shop
		@shops = Store.includes(:products)
	end

	def people
		@users = User.all_cached
	end
	
	def tags
		@tags = Tag.limit(6)
		respond_to do |format|
	      format.html
	      format.json { render :json => @tags }
	    end
	end
private
    def set_trends
   	  #call my trend algo from here
      @tags = Tag.limit(18)
    end

    def cat_type
	    %w[all physical digital].include?(params[:sort]) ? params[:sort] : "all"
  	end

  	def catergory
  	end
end

app/helpers/discover_helper.rb
module DiscoverHelper
end

app/views/discover/_discover_sub_nav.html.erb
<div class="row">
	<div class="large-12 columns">
		<div class="section-container horizontal-nav" data-section="horizontal-nav">
			<section class="section  discoverProducts <%= params[:action] == 'discover' ? 'active':'' %>">
			  <p class="title"> <%= link_to 'Products',discover_path, :remote => true %>  </p>
			</section>
			<section class="section  discoverShops <%= params[:action] == 'shop' ? 'active':'' %>">
			  <p class="title"> <%= link_to 'Shops',discover_shops_path, :remote => true %> </p>
			</section>
			<section class="section  discoverPeople <%= params[:action] == 'people' ? 'active':'' %>">
			  <p class="title"> <%= link_to 'People',discover_people_path, :remote => true %></p>
			</section>
		</div>
	</div>
</div>

app/views/discover/_people.html.erb
<div class="row">
	<div class="large-12 columns">
		<h3> People </h3>
		<% @users.each do |user| %>
			<hr>
			<h4> <%= user.full_name %><small> Subscribe button here </small> <small>  <%= link_to "Visit profile", profile_path(user.username),   class: "right" %> </small></h4> 
		<% end %>
	</div>
</div>

app/views/discover/_products.html.erb
<div class="row">
  <div class="large-12 columns">

    <div class="large-9 columns">
      <dl class="sub-nav">
        <dt>Filter:</dt>
        <dd class="<%= cat_type == "all" ? "active" : "" %> "> <%= link_to "All", sort: "all", :remote => true %></dd>
        <dd class="<%= cat_type == "physical" ? "active" : "" %> "> <%= link_to "Physical", sort: "physical", :remote => true %> </dd>
        <dd class="<%= cat_type == "digital" ? "active" : "" %> "> <%= link_to "Digital", sort: "digital", :remote => true %> </dd>
      </dl>
    </div>
    <div class="large-3 columns">
      <a href="#" data-dropdown="category-dropdown"> All Categories </a>
      <ul id="category-dropdown" class="f-dropdown" data-dropdown-content>
        <% @categories.each do |category| %>
          <!-- need to add one more col in product category to make this work!-->
          <li><%= link_to category.category, params.merge(sort: params[:sort],category: category.category), :remote => true  %></li>
        <% end %>
      </ul>
    </div>

    <div class="large-12 columns">
      <% @products.each do |product| %> 
       <a href="<%= product_url(:subdomain => product.store.store_name,:number => product.random_no) %>" style="color: black; text-decoration:none;">
          <div class="product" style="height: 300px; width: 200px; display: inline-block; margin: 5px; vertical-align: top;">
            <img style="height: 200px; width: 200px;" src="<%= product.cover("thumb_big") %>"/> 
             <br>
            <div class="product_text">
              <p class="product_title" style="border-bottom: 1px solid black;"> <%= truncate(product.product_title, length: 23)%></p>
            </div>
          </div>
        </a>
      <% end %>
    </div>


  </div>
</div>
<%#params[:sort] %>
<%#params[:category] %>

<!--
<%#@categories.each do |category| %>
  <hr>
  <h4> <%#category.category %><small> ->  <%#category.category_type %></small> <small><a class="right" href="#">See all</a></small> </h4> 
  <%#category.products.each do |product| %> 
     <a href="<%#product_url(:subdomain => product.store.store_name,:number => product.random_no) %>" style="color: black; text-decoration:none;">
        <div class="product" style="height: 300px; width: 200px; display: inline-block; margin: 5px; vertical-align: top;">
          <img style="height: 200px; width: 200px;" src="<%#product.cover("thumb_big") %>"/> 
           <br>
          <div class="product_text">
            <p class="product_title" style="border-bottom: 1px solid black;"> <%#truncate(product.product_title, length: 23)%></p>
            <p class="product_title"> <%#truncate(product.description, length: 80)%></p>
          </div>
        </div>
  </a>
  <%#end %>
<%#end %>
!-->

app/views/discover/_shops.html.erb
<div class="row">
  <div class="large-12 columns">
	<h3>Shops</h3>
	<% @shops.each do |shop| %>
	  	<hr>
	  	<h4> <%= shop.store_name %> <small>  <%= link_to "Visit #{shop.store_name}", root_url(:subdomain => shop.store_name), class: "right" %> </small></h4> 
	      <% shop.products.each do |product| %>    
	        <div class="product" style="height: 100px; width: 100px; display: inline-block; margin: 1px; vertical-align: top;">
	           <img style="height: 100px; width: 100px;" src="<%= product.cover("thumb") %>"/> 
	        </div>
	      <% end %>
	<% end %>
  </div>
</div>

app/views/discover/_tag.html.erb
<%= link_to tag_path(tag.name), class: "tag_box", style: "background-image: url(/assets/tags/tags-#{rand(0..11)}.jpg);" do %>
  <span class="tag_name">#<%= tag.name %> </span>
<% end %>
<style>
.tag_box {
	text-decoration: none;
	color: rgba(255, 255, 255, 0.9)!important;
	color: #FFF;
	-webkit-text-shadow: 0 -1px 0 rgba(0,0,0,0.26);
	-moz-text-shadow: 0 -1px 0 rgba(0,0,0,0.26);
	text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.26);
	display: inline-block;
	width: 150px;
	height: 142px;
	overflow: hidden;
	white-space: pre-wrap;
	vertical-align: top;
	padding: 8px 0 0 0;
	position: relative;
}
.tag_name {
	color: #FFF;
	font: bold 11px Arial,Helvetica,sans-serif;
	background: rgba(0, 0, 0, 0.7)!important;
	background: #000;
	border: 1px solid rgba(0, 0, 0, 0.3);
	padding: 1px 5px;
	-webkit-border-radius: 11px;
	-moz-border-radius: 11px;
	border-radius: 11px;
	-webkit-box-shadow: 0 1px 5px rgba(0, 0, 0, 0.45);
	-moz-box-shadow: 0 1px 5px rgba(0,0,0,0.45);
	box-shadow: 0 1px 5px rgba(0, 0, 0, 0.45);
	position: absolute;
	left: 8px;
	bottom: 8px;
}
</style>

app/views/discover/_trending.html.erb
<div class="row">
	<div class="large-12 columns">
		<h4>Trending</h4>
		<hr>
		<% @tags.each do |tag| %>
			<%= render partial: 'tag', locals: {tag: tag } %>
		<% end %>
	</div>
</div>
<br><br>

app/views/discover/discover.html.erb
<%= render 'trending' %>
<%= render 'discover_sub_nav' %>
<div id="discoverContent"> 
	<%= render 'products' %>
</div>


<%= javascript_tag do %>
	$(function () {
		Discover.initialize();
	})
<% end %>

app/views/discover/discover.js.erb
$("section.active").removeClass("active");
$('.discoverProducts').addClass('active');
$("#discoverContent").html('<%= escape_javascript(render 'products') %>');

app/views/discover/people.html.erb
<%= render 'trending' %>
<%= render 'discover_sub_nav' %>
<%= render 'people' %>

app/views/discover/people.js.erb
$("section.active").removeClass("active");
$('.discoverPeople').addClass('active');
$("#discoverContent").html('<%= escape_javascript(render 'people') %>');

app/views/discover/shop.html.erb
<%= render 'trending' %>
<%= render 'discover_sub_nav' %>
<br><br>
<%= render 'shops' %>
<br><br>

app/views/discover/shop.js.erb
$("section.active").removeClass("active");
$('.discoverShops').addClass('active');
$("#discoverContent").html('<%= escape_javascript(render 'shops') %>');